### ISSUE TITLE
Fix giscus: 'An error occurred: giscus is not installed'

### ISSUE THREAD

**Issue by shubham-kshetre** [linux-club-dev/linux-club-web#2]
**Describe the bug**
The comment section is throwing "An error occurred: giscus is not installed"

**To Reproduce**
1. Go 'https://linux-club.vercel.app/blog'
2. Choose blog
3. Scroll down to 'bottom'
4. See error 'giscus is not installed'

**Expected behavior**
load comment button should load comment section

**Screenshots**
![image](https://github.com/linux-club-dev/linux-club-web/assets/90211115/e1571d78-3952-4f96-b7dc-a7236dfe665a)

**Before getting assigned, kindly discuss your approach to solve the problem**

**Comment by shubham-kshetre** [comment]
https://webtech-note.com/posts/giscus-comment-system

**Comment by SAYUK09** [comment]
@shubham-kshetre 
Here's the PR with brief information
https://github.com/linux-club-dev/linux-club-web/pull/6

**Comment by shubham-kshetre** [comment]
[PR](https://github.com/linux-club-dev/linux-club-web/pull/6) from @SAYUK09 has been merged regarding this issue and comments are working fine.
